### ISSUE TITLE
Contributor Guidelines suggestions

### ISSUE THREAD

**Issue by Sei-Lisa** [AVsitter/avsitter.github.io#15]
The bug that surfaced in https://github.com/AVsitter/AVsitter/pull/33 prompted me to add some guidelines about how the commits should be created and how they should appear in the history.

It probably won't be easy to word this in a way suitable for the contributor guidelines, but here we go...

- Commits should change one thing at a time. By that I don't mean one line at a time, or one character at a time. More like one "atomic" feature at a time, so that the repository is in a working state after every commit, but trying to avoid commits that make several unrelated changes. There are several purposes: to ease review by others to ensure there are no new problems, to ease checking the history and to ease rolling back a commit, should that be necessary.
  - For the latter reason, it's best if PRs are not squashed. I usually use "Rebase and merge", though "Merge" would work as well. (*) For small amendments to the PR, e.g. something that was overlooked in one of the commits, it's best if the submitter amends the commits as necessary and force-pushes.
- The commit message should describe the change as best as possible. The first line is the title and should summarize the commit in about 70 chars if possible; if more explanations or some clarifications are necessary, leave a blank line under the title and explain further below that.
- Indentation and formatting changes cause very messy diffs, because they tend to sync with the wrong lines. It's best to separate those from the functionality-changing ones, while announcing that there are no code changes otherwise, in order for the reviewer to focus on what's important without having to decipher the messy diffs.
- Sometimes, while making a change we spot a part of the code that needs an unrelated change, and we go ahead and fix it before we forget. For those cases, git provides the `-p` flag for the `commit` and `add` commands, which allows selecting which changed lines go into the commit and which ones don't, or even editing the diff of what goes into the commit. To avoid mixing unrelated changes, you can make use of that.

(*) Both have pros and cons. "Rebase and merge" adds the new history at the top of master, which is good; however, the commit ID changes, leaving a lingering branch that git complains about when trying to delete it, saying it's not merged into master (which isn't true). This one leaves the repository history in the cleanest state. "Merge pull request", on the other hand, merges master and the PR commits without adding them at the top, and creates an extra merge commit. I find that a bit messier most of the time. I'm not a big friend of merge commits when they're not strictly necessary.

**Comment by Sei-Lisa** [comment]
In addition to the above:

- File renames should have their own separate commit. Don't rename and change a file in the same commit; otherwise it's nearly impossible to see what changed.

**Comment by codeviolet** [comment]
All contributors should be aware of these, and because I am relatively new to GitHub I have appreciated you telling me when I have strayed from them. Eventually, I hope a refined version of this list will be included or referenced by https://avsitter.github.io/contribute.html (or wherever contributor guidelines are to be kept).
