### ISSUE TITLE
AVsitter availability

### ISSUE THREAD

**Issue by GypsyCirceofHelios** [AVsitter/avsitter.github.io#2]
I've just come in from MP in second Life.  AVSitter 1 & 2 are both selling for 2,999 L
How else can I obtain the new CC versions?  
Thank You
Gypsy
(DianeHolden007)

https://marketplace.secondlife.com/p/AVSITTER2-REVOLUTIONARY-Multi-Pose-System/2277498

**Comment by codeviolet** [comment]
Hi. Thanks for the question. At the moment you would need to get the scripts directly from the repository https://github.com/AVsitter/AVsitter2 or ask someone inworld to send a folder containing the unboxed scripts to you. Other methods may be made available soon.
