### ISSUE TITLE
Suggestion for `The AVpos notecard` documentation page

### ISSUE THREAD

**Issue by AurynBeorn** [AVsitter/avsitter.github.io#25]
At the end of this page there are a few extra commands (HELPER, KFM, LROT, WARN 0, WARN 2) that are linked to an external Q&A page in the avsitter.com domain.

My suggestion is bringing that documentation into github, perhaps creating a `Special Commands` submenu under the Step by Step Guides submenu. Then, each page would link to the original Q&A page they come from at the end (and beginning?), for those that want to read the whole discussion in those pages.

What do you think of this?

**Comment by Sei-Lisa** [comment]
:+1: for bringing the documentation to the site. The Q&A is not really a format suitable for a reference manual.

However, I'd like to see compact descriptions of these commands too, not just step-by-step guides. Something more exhaustive than the current one-liners, but without going through an example step by step.

**Comment by AurynBeorn** [comment]
I think I used the wrong word. I didn't mean a `Special Commands` as a subset of the `Step by Step Guides`, but an independent submenu _below_ it. Sorry I didn't express it correctly.

I also agree with your suggestion: something compact for the main `The AVpos notecard` page, and then the detailed explanation, with examples if needed, under this `Special Commands` section - unrelated to the `Step by Step Guides`.

**Comment by Sei-Lisa** [comment]
Ahh okay. "under" suggested "inside" to me, sorry.

Thinking about it, maybe we can leave the one-liners and just make the links point to the Special Commands page where they are described in detail.
