### ISSUE TITLE
Suggest adding current version to the comments of each script

### ISSUE THREAD

**Issue by hodgegw** [AVsitter/avsitter.github.io#46]
The folowing is a copy/paste from each one of the AV Sitter scripts. In them it says (the begining comments):
/*
 * [AV]sitB - Main Memory script - needs [AV]sitA to work
 * (OpenSim version)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * Copyright © the AVsitter Contributors (http://avsitter.github.io)
 * AVsitter™ is a trademark. For trademark use policy see:
 * https://avsitter.github.io/TRADEMARK.mediawiki
 *
 * Please consider supporting continued development of AVsitter and
 * receive automatic updates and other benefits! All details and user
 * instructions can be found at http://avsitter.github.io
 */

I would like to suggest that you update the version number to reflect the current release of "AV Sitter2.2-03.01". I believe this would lessen any cunfusion about what's out there available from sources other than github.

Thanks for the consideration.

Regards,
Gary Hodges (a.k.a. Gary Kohime in SL & OpenSim)

**Comment by Sei-Lisa** [comment]
Thanks for the suggestion. That's reasonable, I think it can be incorporated through a mechanism similar to [CVS keywords](http://web.mit.edu/~xela/WWW/cvs-keywords.html), using the build system to set them.
