### ISSUE TITLE
Link for SET information broken

### ISSUE THREAD

**Issue by Sei-Lisa** [AVsitter/avsitter.github.io#6]
In https://avsitter.github.io/avsitter2_avpos.html#set there is a link to https://avsitter.github.io/avsitter2_sittargets.html#assigningsittargets

That link doesn't go to the appropriate anchor. Maybe the intended destination can be adjusted to add an anchor with the name "assigningsittargets".

**Comment by codeviolet** [comment]
The anchors are automatically generated by the headings... in this particular case, in the file [avsitter2_sittargets.md](https://github.com/AVsitter/avsitter.github.io/blob/master/pages/avsitter2/avsitter2_sittargets.md), and I had added the text "(special/advanced only)" to that heading, and forgotten to update the link(s) pointing there. In this case I think it will be best fixed simply by removing the anchor from the offending ```href``` in avsitter2_avpos.html. I will make the appropriate change. As it is such a simple change I will commit to the main branch.
